spring:

  # Nome dell'applicazione
  application:
    name: bugboard26

  # Connessione al database PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5433/bugboard26
    username: bugboard
    password: secret
    driver-class-name: org.postgresql.Driver

  # JPA / Hibernate
  jpa:
    # Crea/aggiorna le tabelle automaticamente all'avvio
    # Va bene ora in sviluppo — lo cambieremo in produzione
    open-in-view: false 
    hibernate:
      ddl-auto: update
    # Mostra le query SQL nel terminale
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Porta su cui gira il server (default 8080)
server:
  port: 8080